/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pertemuan8;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class logistik extends javax.swing.JFrame {

    /**
     * Creates new form TugasJtabel
     */
    DefaultTableModel model;
    int index, confirm;
    String noResi,
            namaPengririm,
            namaPenerima,
            noTlpPenerima,
            alamat,
            jenisBarang,
            berat,
            jenisPengiriman,
            modePengiriman,
            bw,
            pk,
            bk,
            pw,
            status;

    public logistik() {
        initComponents();

        Object kolom[] = {"No Resi", "Nama Pengirim", "Nama Penerima", "No Tlp", "Alamat Penerima", "Jenis Barang", "Berat", "Jenis Pengiriman", "Mode Pengiriman", "Opsi Extra", "Status"};
        Object data[][] = {{"001-22", "Abim", "jaki", "0865", "Us", "Makanan", "2 Kg", "JNE", "Express", "Bubble Wrap", "Selesai"}};

        model = new DefaultTableModel(data, kolom);
        jTableHasil.setModel(model);

        JOptionPane.showMessageDialog(this, "Hallo, Selamat datang diprogram pendataan Logistik.", "Info", JOptionPane.INFORMATION_MESSAGE);
        JOptionPane.showMessageDialog(this, "Silahkan isi table sesuai dengan data customer.", "Info", JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupModePengiriman = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtNoResi = new javax.swing.JTextField();
        txtNamaPengirim = new javax.swing.JTextField();
        txtNamaPenerima = new javax.swing.JTextField();
        txtNoTlp = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaAlamat = new javax.swing.JTextArea();
        jCBJenisbarang = new javax.swing.JComboBox<>();
        txtBeratBarang = new javax.swing.JTextField();
        jCBJenisPengiriman = new javax.swing.JComboBox<>();
        jRadioButtonExpress = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jCheckBoxBubbleWrap = new javax.swing.JCheckBox();
        jCheckBoxPackingKaya = new javax.swing.JCheckBox();
        jCheckBoxDoubleKarton = new javax.swing.JCheckBox();
        jCheckBoxPlastikWrap = new javax.swing.JCheckBox();
        jCBStatusPengiriman = new javax.swing.JComboBox<>();
        btnSimpan = new javax.swing.JButton();
        jButtonHasilIsiTabel = new javax.swing.JButton();
        jButtonHapusBarisTabel = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableHasil = new javax.swing.JTable();
        jButtonKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nama Pengirim");

        jLabel2.setText("Nama Penerima");

        jLabel3.setText("No RESI");

        jLabel4.setText("No Tlp (Penerima)");

        jLabel5.setText("Status Pengiriman");

        jLabel6.setText("Berat");

        jLabel7.setText("Jenis barang");

        jLabel8.setText("Jenis Pengiriman");

        jLabel12.setText("Alamat tujuan");

        jLabel13.setText("Opsi Extra");

        jLabel14.setText("Mode pengiriman");

        jLabel16.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel16.setText("Data pengiriman");

        txtNoResi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoResiActionPerformed(evt);
            }
        });

        jTextAreaAlamat.setColumns(20);
        jTextAreaAlamat.setRows(5);
        jScrollPane1.setViewportView(jTextAreaAlamat);

        jCBJenisbarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Makanan", "Elektronik", "Pakaian", "Kendaraan", "Barang Pecah belah" }));

        jCBJenisPengiriman.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "JNE", "JNT", "Wahana", "Go Send" }));

        btnGroupModePengiriman.add(jRadioButtonExpress);
        jRadioButtonExpress.setText("Express");

        btnGroupModePengiriman.add(jRadioButton2);
        jRadioButton2.setText("Reguler");

        jCheckBoxBubbleWrap.setText("Bubble wrap");

        jCheckBoxPackingKaya.setText("Packing kayu");

        jCheckBoxDoubleKarton.setText("Double karton");

        jCheckBoxPlastikWrap.setText("Plastik wrapping");

        jCBStatusPengiriman.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Penjemputan Kurir", "Dalam Perjalanan", "Barang Diterima", "Retur" }));

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        jButtonHasilIsiTabel.setText("Hapus Isi Tabel");
        jButtonHasilIsiTabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHasilIsiTabelActionPerformed(evt);
            }
        });

        jButtonHapusBarisTabel.setText("Hapus Baris Tabel");
        jButtonHapusBarisTabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHapusBarisTabelActionPerformed(evt);
            }
        });

        jTableHasil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No Resi", "Nama Pengiriman", "Nama Penerima", "No Tlp", "Alamat Tujuan", "Jenis Baranag", "Berat", "Jenis Pengiriman", "Mode Pengiriman", "Opsi Extra", "Status Pengiriman"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableHasil.setColumnSelectionAllowed(true);
        jScrollPane3.setViewportView(jTableHasil);
        jTableHasil.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jButtonKeluar.setText("Keluar");
        jButtonKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSimpan)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonHasilIsiTabel)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonHapusBarisTabel)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonKeluar))
                    .addComponent(jLabel16)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNoResi)
                                    .addComponent(txtNamaPengirim)
                                    .addComponent(txtNamaPenerima, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel12))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(txtNoTlp, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(19, 19, 19)
                                .addComponent(jCBStatusPengiriman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13))
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCheckBoxBubbleWrap)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCheckBoxPackingKaya))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButtonExpress)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButton2))
                                    .addComponent(jCBJenisPengiriman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCBJenisbarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtBeratBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCheckBoxDoubleKarton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBoxPlastikWrap))))))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1061, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNoResi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNamaPengirim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNamaPenerima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNoTlp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jCBJenisbarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtBeratBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jCBJenisPengiriman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jRadioButtonExpress)
                            .addComponent(jRadioButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jCheckBoxBubbleWrap)
                            .addComponent(jCheckBoxPackingKaya))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxDoubleKarton)
                            .addComponent(jCheckBoxPlastikWrap))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jCBStatusPengiriman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(jButtonHasilIsiTabel)
                    .addComponent(jButtonHapusBarisTabel)
                    .addComponent(jButtonKeluar))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNoResiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoResiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoResiActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
//        data pelanggan
        noResi = txtNoResi.getText();
        namaPengririm = txtNamaPengirim.getText();
        namaPenerima = txtNamaPenerima.getText();
        noTlpPenerima = txtNoTlp.getText();
        alamat = jTextAreaAlamat.getText();

//        data barang
        jenisBarang = jCBJenisbarang.getSelectedItem().toString();
        berat = txtBeratBarang.getText();
        jenisPengiriman = jCBJenisPengiriman.getSelectedItem().toString();
//      mode pengiriman
        if (jRadioButtonExpress.isSelected()) {
            modePengiriman = "Express";
        } else {
            modePengiriman = "Reguler";
        }
//        checkbox
        if (jCheckBoxBubbleWrap.isSelected()) {
            bw = "Bubble Wrap";
        } else {
            bw = "";
        }
        if (jCheckBoxPackingKaya.isSelected()) {
            pk = "Packing Kayu";
        } else {
            pk = "";
        }
        if (jCheckBoxDoubleKarton.isSelected()) {
            bk = "Bubble Karton";
        } else {
            bk = "";
        }
        if (jCheckBoxPlastikWrap.isSelected()) {
            pw = "Plastik Wrapping";
        } else {
            pw = "";
        }
        status = jCBStatusPengiriman.getSelectedItem().toString();
//        memasukkan ke table
        model.addRow(new Object[]{noResi, namaPengririm, namaPenerima, noTlpPenerima, alamat, jenisBarang, berat, jenisPengiriman, modePengiriman, bw, pk, bk, pw, status});
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void jButtonHapusBarisTabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusBarisTabelActionPerformed
        // TODO add your handling code here:
        confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus data pada baris tabel yang anda pilih ?",
                "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            index = jTableHasil.getSelectedRow();
            model.removeRow(index);
            jTableHasil.setModel(model);
            JOptionPane.showMessageDialog(this, "Data berhasil dihapus.", "Info", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonHapusBarisTabelActionPerformed

    private void jButtonHasilIsiTabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHasilIsiTabelActionPerformed
        // TODO add your handling code here:
        confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus semua data di tabel?",
                "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            model.setRowCount(0); // Menghapus semua baris
            JOptionPane.showMessageDialog(this, "Semua data berhasil dihapus.", "Info", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonHasilIsiTabelActionPerformed

    private void jButtonKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKeluarActionPerformed
        // TODO add your handling code here:
        confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin keluar dari program ?",
                "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            dispose();
            JOptionPane.showMessageDialog(this, "Program Keluar Terimakasih", "Info", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonKeluarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(logistik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(logistik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(logistik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(logistik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new logistik().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupModePengiriman;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton jButtonHapusBarisTabel;
    private javax.swing.JButton jButtonHasilIsiTabel;
    private javax.swing.JButton jButtonKeluar;
    private javax.swing.JComboBox<String> jCBJenisPengiriman;
    private javax.swing.JComboBox<String> jCBJenisbarang;
    private javax.swing.JComboBox<String> jCBStatusPengiriman;
    private javax.swing.JCheckBox jCheckBoxBubbleWrap;
    private javax.swing.JCheckBox jCheckBoxDoubleKarton;
    private javax.swing.JCheckBox jCheckBoxPackingKaya;
    private javax.swing.JCheckBox jCheckBoxPlastikWrap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButtonExpress;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableHasil;
    private javax.swing.JTextArea jTextAreaAlamat;
    private javax.swing.JTextField txtBeratBarang;
    private javax.swing.JTextField txtNamaPenerima;
    private javax.swing.JTextField txtNamaPengirim;
    private javax.swing.JTextField txtNoResi;
    private javax.swing.JTextField txtNoTlp;
    // End of variables declaration//GEN-END:variables
}
